spring:
  application:
    name: tutor-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Unicorn;encrypt=true;trustServerCertificate=true
    username: Kenneth
    password: 12345678
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka