spring:
  application:
    name: gatewayApi

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
          fillters:
            - name: UserFilter
              args:
                - firstName: John
                - lastName: Doe

        - id: orderservice
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**